/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exam;

public class App  {
    public void getGreeting() {
        
       System.out.println("Hellow Country");   
    }   

    public void selected(){
        System.out.println("Hellow you are selected");
    }
    public void selected(int x){
        System.out.println("HEllow you are not selected");
    }
    public static void main(String[] args) {
      Home home = new Home();
      home.setVisible(true);
}
}
